#pragma once

#include <builtinFonts/notoserif_12_bold.h>
#include <builtinFonts/notoserif_12_bolditalic.h>
#include <builtinFonts/notoserif_12_italic.h>
#include <builtinFonts/notoserif_12_regular.h>
#include <builtinFonts/notoserif_14_bold.h>
#include <builtinFonts/notoserif_14_bolditalic.h>
#include <builtinFonts/notoserif_14_italic.h>
#include <builtinFonts/notoserif_14_regular.h>
#include <builtinFonts/notoserif_16_bold.h>
#include <builtinFonts/notoserif_16_bolditalic.h>
#include <builtinFonts/notoserif_16_italic.h>
#include <builtinFonts/notoserif_16_regular.h>
#include <builtinFonts/notoserif_18_bold.h>
#include <builtinFonts/notoserif_18_bolditalic.h>
#include <builtinFonts/notoserif_18_italic.h>
#include <builtinFonts/notoserif_18_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/lexend_12_bold.h>
#include <builtinFonts/lexend_12_regular.h>
#include <builtinFonts/lexend_14_bold.h>
#include <builtinFonts/lexend_14_regular.h>
#include <builtinFonts/lexend_16_bold.h>
#include <builtinFonts/lexend_16_regular.h>
#include <builtinFonts/lexend_18_bold.h>
#include <builtinFonts/lexend_18_regular.h>
#include <builtinFonts/bokerlam_12_bold.h>
#include <builtinFonts/bokerlam_12_italic.h>
#include <builtinFonts/bokerlam_12_regular.h>
#include <builtinFonts/bokerlam_14_bold.h>
#include <builtinFonts/bokerlam_14_italic.h>
#include <builtinFonts/bokerlam_14_regular.h>
#include <builtinFonts/bokerlam_16_bold.h>
#include <builtinFonts/bokerlam_16_italic.h>
#include <builtinFonts/bokerlam_16_regular.h>
#include <builtinFonts/bokerlam_18_bold.h>
#include <builtinFonts/bokerlam_18_italic.h>
#include <builtinFonts/bokerlam_18_regular.h>

// Magnus theme fonts
#include <builtinFonts/ebgaramond_12_semibold.h>
#include <builtinFonts/ebgaramond_12_italic.h>
#include <builtinFonts/ebgaramond_18_semibold.h>
#include <builtinFonts/courierprime_10_regular.h>
#include <builtinFonts/courierprime_12_regular.h>
#include <builtinFonts/courierprime_12_bold.h>
#include <builtinFonts/courierprime_14_regular.h>

// Atkinson Hyperlegible — reader body (uncompressed)
#include <builtinFonts/atkinson_12_regular.h>
#include <builtinFonts/atkinson_12_bold.h>
#include <builtinFonts/atkinson_12_italic.h>
#include <builtinFonts/atkinson_14_regular.h>
#include <builtinFonts/atkinson_14_bold.h>
#include <builtinFonts/atkinson_14_italic.h>
#include <builtinFonts/atkinson_16_regular.h>
#include <builtinFonts/atkinson_16_bold.h>
#include <builtinFonts/atkinson_16_italic.h>
#include <builtinFonts/atkinson_18_regular.h>
#include <builtinFonts/atkinson_18_bold.h>
#include <builtinFonts/atkinson_18_italic.h>
